/* tslint:disable */
/**
 * DO NOT MODIFY!
 *
 * This file is generated by routekit.
 */

export const ROUTES = {
  f: 11,
  p: "/",
  c: [{
    f: 3,
    p: "completed",
    d: 1
  }, {
    f: 3,
    p: "active",
    d: 2
  }],
  d: 0
};